Mini_Project/community/community/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/',include('home.urls', namespace='home')),
    path('about/',views.about,name='About'),
    path('',views.testpage2.as_view(),name='testpage2'),
    #path('',views.welcome,name='welcome'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mini_Project/community/home/urls.py
from django.urls import path
from django.conf.urls import url
from home import views
from django.contrib.auth.views import login,logout
app_name= 'home'
urlpatterns= [
    path('login/',login,{'template_name': 'home/login.html'}),
    path('about/',views.about,name='About'),
    path('register/',views.register,name='register'),
    path('logout/',logout,{'template_name': 'home/homepage.html'}),
    path('',views.list_of_questions,name='testpage'),
    path('ask/', views.ask_question,name='ask_question'),
    path('profile/',views.view_profile, name='view_profile'),
    path('profile/edit/',views.edit_profile, name='edit_profile'),
    path('profile/edit/change-password/',views.change_password, name='change_password'),
    path('profile/password/',views.redirect_password, name='redirect_password'),
    path('<slug:slug>/',views.view_question,name='view_question'),
    path('<slug:slug>/answer/',views.add_answer,name='add_answer')
]

Mini_Project/community/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import slugify
# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    description = models.CharField(max_length=264, default='')
    occupation = models.CharField(max_length=20, default='')
    email = models.EmailField(default='')
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile=UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)
#
# class Document(models.Model):
#     description = models.CharField(max_length=255, blank=True)
#     document = models.FileField(upload_to='documents/')
#     uploaded_at = models.DateTimeField(auto_now_add=True)
class Question(models.Model):
    title = models.CharField(max_length=264)
    slug = models.SlugField(max_length=264)
    content = models.TextField(default='')
    author = models.ForeignKey(User, related_name='questions', on_delete=models.CASCADE)
    published = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        self.slug=slugify(self.title)
        super(Question, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('home:view_question', args=[self.slug])

    def __str__(self):
        return self.title

class Answer(models.Model):
    question=models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)
    user= models.CharField(max_length=250)
    email=models.EmailField()
    body=models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)
    # upvotes=models.BooleanField(default='0')
    def approved(self):
        self.approved =True
        self.save()

    def __str__(self):
        return self.user

Mini_Project/community/home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from home.models import Answer, Question
#from uploads.core.models import Document

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = ('username',
        'first_name',
        'last_name',
        'email',
        'password1',
        'password2'
    )

    def save(self,commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
        'first_name',
        'last_name',
        'email',
        'password',
        )
#
# class DocumentForm(forms.ModelForm):
#     class Meta:
#         model = Document
#         fields = ('description', 'document', )
class AskQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields =(
        'title',
        'content',
        )

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = (
        'body',
        )

Mini_Project/community/home/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.contrib.auth import update_session_auth_hash
from home.forms import (
    RegistrationForm,
    EditProfileForm,
    AnswerForm,
    AskQuestionForm,
)
from django.contrib.auth.models import User
from home.models import Question,Answer
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
'''
def index(request):
    my_dict={'insert_me':"Hello I am from home/index.html!"}
    return render(request,'home/index.html',context=my_dict)
'''
def welcome(request):
    return render(request,'home/homepage.html')

#def login(request):
#    return render(request,'home/login.html')

def register(request):
    if request.method=='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account/login')
        else:
            redirect('/account/register')
    else:
        form = RegistrationForm()

        args={'form':form}
        return render(request, 'home/register.html', args)

def about(request):
    return render(request, 'home/about.html')

class testpage(TemplateView):
    template_name='home/dashboard.html'


class testpage2(TemplateView):
    template_name='home/homepage.html'

@login_required
def view_profile(request):
    args= {'user': request.user}
    return render(request, 'home/profile.html',args)

@login_required
def edit_profile(request):
    if request.method== 'POST':
        form= EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')
        else:
            return redirect('/account/profile/edit')

    else:
        form= EditProfileForm( instance=request.user)
        args = {'form': form}
        return render(request, 'home/edit_profile.html', args)

@login_required
def change_password(request):
    if request.method=="POST":
        form= PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
        else:
            return redirect('/account/profile/edit/change-password')
    else:
        form= PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'home/change_password.html', args)


def redirect_password(request):
    return redirect('/account/profile/edit/change-password')

#
# def model_form_upload(request):
#     if request.method == 'POST':
#         form = DocumentForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('/account/feed')
#     else:
#         form = DocumentForm()
#     return render(request, 'home/model_form_upload.html', {
#         'form': form
#     })
def list_of_questions(request):
    question=Question.objects.all()
    paginator=Paginator(question, 3)
    page = request.GET.get('page')
    try:
        questions=paginator.page(page)
    except PageNotAnInteger:
        questions=paginator.page(1)
    except EmptyPage:
        questions=paginator.page(paginator.num_pages)
    return render(request, 'home/dashboard.html', {'questions':questions, 'page':page} )

def view_question(request, slug):
    question = get_object_or_404(Question, slug=slug)
    args={'question':question}
    return render(request, 'home/view_question.html', args)

def add_answer(request,slug):
    question=get_object_or_404(Question, slug=slug)
    if request.method== 'POST':
        form=AnswerForm(request.POST)
        if form.is_valid():
            answer=form.save(commit=False)
            answer.user=request.user
            answer.email=request.user.email
            answer.question=question
            answer.save()
            return redirect('home:view_question',slug=question.slug)
    else:
        form=AnswerForm()
        return render(request, 'home/add_answer.html', {'form':form, 'question':question} )

def ask_question(request):
    if request.method == "POST":
        form= AskQuestionForm(request.POST)
        if form.is_valid():
            question=form.save(commit=False)
            question.author=request.user
            question.save()
            return redirect('home:view_question', slug=question.slug)
    else:
        form = AskQuestionForm()
        args = {'form': form}
        return render(request, 'home/ask_question.html', args)

Mini_Project/community/templates/home/about.html
{% extends 'base.html' %}

  {% block head %}
    <title>About</title>
  {% endblock %}

  {% block body %}
  <style media="screen">
    img{
      border-radius: 50%
    }
  </style>
  <div class="container">
  <div class="jumbotron">
      <h1><strong>This site is made by Aishwarya and Ryan. It would not have been possible without our dedication, rigorous efforts and our guide who kept on motivating us to do better and achieve our fullest potential</strong> </h1>
      <br>
      <p>
        <strong>Contact:</strong>
      </p>
      <div class="row">
          <div class="col-sm-3">
            <p>
              <strong>Aishwarya Sebin</strong>
            </p>
            <p>
              <strong>Email:</strong> aishsebin@gmail.com
            </p>
            <p>
              <strong>Phone:</strong> <i>9833760985</i>
            </p>
          </div>
          <div class="col-sm-3">
            <p>
                {% load staticfiles %}
              <img src="{% static 'community/aish.jpg' %}" style="width: 100px;height:100px;"class="img-responsive img-rounded">
            </p>
          </div>
          <div class="col-sm-3">
            <p>
              <strong>Ryan D'Mello</strong>
            </p>
            <p>
              <strong>Email:</strong> dmelloryan11@gmail.com
            </p>
            <p>
              <strong>Phone:</strong> <i>7507858717</i>
            </p>
          </div>
          <div class="col-sm-3">
            <p>
                {% load staticfiles %}
              <img src="{% static 'community/ryan.jpg' %}" style="width: 100px;height:100px;"class="img-responsive img-rounded">
            </p>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}

Mini_Project/community/templates/home/add_answer.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head %}
<meta charset="utf-8">
<title>Answer: {{ question.title }}</title>
{% endblock %}

{% block body %}
<div class="container">

<div class="row">
  <div class="col-md-8">
    <div class="page-header">
<h1>Add new Answer</h1>
</div>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</div>

</div>


  </div>
{% endblock %}

Mini_Project/community/templates/home/ask_question.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head %}
<meta charset="utf-8">
<title>Ask a Question</title>
{% endblock %}

{% block body %}
<div class="container">

  <h1>Ask a Question</h1>
  <form method="POST" class="post-form">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</div>
{% endblock %}

Mini_Project/community/templates/home/change_password.html
{% extends 'base.html' %}

    {% block head %}

    <meta charset="utf-8">
    <title>Edit Profile</title>
    {% endblock %}


    {% block body %}
    <div class="container">
      <div class="jumbotron">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-success">Submit</button>
        </form>

      </div>
    </div>
    {% endblock %}

Mini_Project/community/templates/home/dashboard.html
{% extends 'base.html' %}

{% block head %}
<meta charset="utf-8">
<title>Feed</title>
{% endblock %}

{% block body %}
<br>
  <div class="container">


      {% for question in questions %}
<div class="jumbotron" style="background-color:#edf2f2">
        <h2><a href ="{{ question.get_absolute_url }}">{{ question.title }}</a></h2>
        <p>Written by {{ question.author }} on {{ question.published }}</p>
        <hr>
        {{ question.content|truncatewords:40|linebreaks }}

        </div>
      {% endfor %}
      {% include 'paginator.html' with page=questions %}

      </div>
{% endblock %}

Mini_Project/community/templates/home/edit_profile.html
{% extends 'base.html' %}

    {% block head %}

    <meta charset="utf-8">
    <title>Edit Profile</title>
    {% endblock %}


    {% block body %}
    <div class="container">
      <div class="jumbotron">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-success">Submit</button>
        </form>

      </div>
    </div>
    {% endblock %}

Mini_Project/community/templates/home/feed.html
{% extends 'base.html' %}

{% block head %}

<meta charset="utf-8">
<title>Feed</title>
{% endblock %}

<!-- {% block body %}
<div class="container">
  <div class="jumbotron">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Submit</button>
    </form>

  </div>
</div>
{% endblock %} -->

Mini_Project/community/templates/home/homepage.html
{% extends 'base.html' %}

    {% block head %}

    <meta charset="utf-8">
    <title>Home</title>
    {% endblock %}


    {% block body %}
    <div class="container">
    <div class="jumbotron">
      <h1>Welcome</h1>

    </div>
    </div>
    {% endblock %}

Mini_Project/community/templates/home/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

    {% block body %}

    <div class="container">
      <div class="jumbotron">
        <div style="text-align: center;">
          <h1>Login</h1>
        </div>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}

          <button type="submit" class="btn btn-success">Login</button>
        </form>
      </div>
    </div>
    {% endblock %}

Mini_Project/community/templates/home/logout.html
{% extends 'base.html' %}

{% block head %}
<title>Logged Out!</title>
{% endblock %}

    {% block body %}

    <div class="container">
      <div class="jumbotron">
        <div style="text-align: center;">
          <h1>Login</h1>
        </div>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}

          <button type="submit" class="btn btn-success">Login</button>
        </form>
      </div>
    </div>
    {% endblock %}

Mini_Project/community/templates/home/profile.html
{% extends 'base.html' %}

    {% block head %}

    <meta charset="utf-8">
    <title>Profile</title>
    {% endblock %}


    {% block body %}
    <div class="container">
    <div class="jumbotron">
      <h1>Profile</h1>
      <p>Username: {{ user }}</p>
      <p>First name: {{ user.first_name }}</p>
      <p>Last name: {{ user.last_name }}</p>
      <p>Email: {{ user.email }}</p>
      <p>Description: {{ user.userprofile.description }} </p>
      <p>Occupation:  {{ user.userprofile.occupation }}</p>
      <p>Number of Questions Asked: {{ user.questions.count }}</p>
      
      <img src="{{ user.userprofile.image.url }}" width="240">
      <br>
      <br>
      <a class="btn btn-outline-success" href="edit/" role="button">Edit Profile</a>
    </div>
    </div>
    {% endblock %}

Mini_Project/community/templates/home/register.html
{% extends 'base.html' %}

{% block head %}
<title>Registration</title>
{% endblock %}

    {% block body %}
    <div class="container">
      <h1>Registration Form</h1>
      <div class="jumbotron">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
      </div>
    </div>
    {% endblock %}

Mini_Project/community/templates/home/view_question.html
{% extends 'base.html' %}

{% block head %}
<meta charset="utf-8">
<title>{{ question.title }}</title>
{% endblock %}

{% block body %}
<br>
  <div class="container">
<div class="jumbotron">
        <h2>{{ question.title }}</h2>
        <p>Written by {{ question.author }} on {{ question.published }}</p>
        <hr>
        {{ question.content|linebreaks }}
</div>
        <hr>
        <h1>Answers</h1>
        <hr>
        <p>Total number of answers: {{ question.answers.count }}</p>
        <a class="btn btn-outline-success" href="{% url 'home:add_answer' slug=question.slug %}" role="button">Leave an Answer</a>
        <hr>
        {% for answer in question.answers.all %}
        <p>{{ answer.created }}</p>
        <p>{{ answer.user }}</p>
        <p>{{ answer.body }}</p>
        <hr>
        {% empty %}
        <p>There are no answers</p>

        {% endfor %}

      </div>
{% endblock %}